### ISSUE TITLE
PERMISSION DENIED access to SecurityGroupService

### ISSUE THREAD

**Issue by PavelOlin** [yandex-cloud/java-sdk#1]
Kotlin code snippet:
```
val securityGroupService: SecurityGroupServiceGrpc.SecurityGroupServiceBlockingStub
val securityGroups = securityGroupService.list(SecurityGroupServiceOuterClass.ListSecurityGroupsRequest.newBuilder()
                .setFolderId(folderId)
                .build()).securityGroupsList
```

During execution this code I got exception: 

`
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at yandex.cloud.api.vpc.v1.SecurityGroupServiceGrpc$SecurityGroupServiceBlockingStub.list(SecurityGroupServiceGrpc.java:602)
`

but I can easy access to all another services (compute, vpc, loadbalancer) .

What can be wrong?

**Comment by vasiliy-briginets** [comment]
> Kotlin code snippet:
> 
> ```
> val securityGroupService: SecurityGroupServiceGrpc.SecurityGroupServiceBlockingStub
> val securityGroups = securityGroupService.list(SecurityGroupServiceOuterClass.ListSecurityGroupsRequest.newBuilder()
>                 .setFolderId(folderId)
>                 .build()).securityGroupsList
> ```
> 
> During execution this code I got exception:
> 
> `io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240) at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221) at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140) at yandex.cloud.api.vpc.v1.SecurityGroupServiceGrpc$SecurityGroupServiceBlockingStub.list(SecurityGroupServiceGrpc.java:602)`
> 
> but I can easy access to all another services (compute, vpc, loadbalancer) .
> 
> What can be wrong?

Hello, Pavel! 
Security Groups is in private preview phase and not available right now. Please wait for public preview announcement.
